[package]
name = "bevy_iced_bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
bevy_iced = "0.1.1"
iced_native = "0.5.1"
